## Translated from common/fluent/hotkeys.ftl
hotkey-context =
    .player = Player
    .spectator = Spectator
    .chat-input = Chat Input
    .menu = Menu
    .editor = Editor

## chat.yaml
hotkey-description-openteamchat = 打开队伍聊天
hotkey-description-opengeneralchat = 打开公共聊天
hotkey-description-togglechatmode = 切换聊天模式
hotkey-description-autocomplete = 自动补全

## control-groups.yaml
hotkey-description-controlgroupselect01 = 选择编队 1
hotkey-description-controlgroupselect02 = 选择编队 2
hotkey-description-controlgroupselect03 = 选择编队 3
hotkey-description-controlgroupselect04 = 选择编队 4
hotkey-description-controlgroupselect05 = 选择编队 5
hotkey-description-controlgroupselect06 = 选择编队 6
hotkey-description-controlgroupselect07 = 选择编队 7
hotkey-description-controlgroupselect08 = 选择编队 8
hotkey-description-controlgroupselect09 = 选择编队 9
hotkey-description-controlgroupselect10 = 选择编队 0
hotkey-description-controlgroupcreate01 = 编组 1
hotkey-description-controlgroupcreate02 = 编组 2
hotkey-description-controlgroupcreate03 = 编组 3
hotkey-description-controlgroupcreate04 = 编组 4
hotkey-description-controlgroupcreate05 = 编组 5
hotkey-description-controlgroupcreate06 = 编组 6
hotkey-description-controlgroupcreate07 = 编组 7
hotkey-description-controlgroupcreate08 = 编组 8
hotkey-description-controlgroupcreate09 = 编组 9
hotkey-description-controlgroupcreate10 = 编组 0
hotkey-description-controlgroupaddto01 = 加入编队 1
hotkey-description-controlgroupaddto02 = 加入编队 2
hotkey-description-controlgroupaddto03 = 加入编队 3
hotkey-description-controlgroupaddto04 = 加入编队 4
hotkey-description-controlgroupaddto05 = 加入编队 5
hotkey-description-controlgroupaddto06 = 加入编队 6
hotkey-description-controlgroupaddto07 = 加入编队 7
hotkey-description-controlgroupaddto08 = 加入编队 8
hotkey-description-controlgroupaddto09 = 加入编队 9
hotkey-description-controlgroupaddto10 = 加入编队 0
hotkey-description-controlgroupcombinewith01 = 与编队 1 合并
hotkey-description-controlgroupcombinewith02 = 与编队 2 合并
hotkey-description-controlgroupcombinewith03 = 与编队 3 合并
hotkey-description-controlgroupcombinewith04 = 与编队 4 合并
hotkey-description-controlgroupcombinewith05 = 与编队 5 合并
hotkey-description-controlgroupcombinewith06 = 与编队 6 合并
hotkey-description-controlgroupcombinewith07 = 与编队 7 合并
hotkey-description-controlgroupcombinewith08 = 与编队 8 合并
hotkey-description-controlgroupcombinewith09 = 与编队 9 合并
hotkey-description-controlgroupcombinewith10 = 与编队 0 合并
hotkey-description-controlgroupjumpto01 = 跳转至编队 1
hotkey-description-controlgroupjumpto02 = 跳转至编队 2
hotkey-description-controlgroupjumpto03 = 跳转至编队 3
hotkey-description-controlgroupjumpto04 = 跳转至编队 4
hotkey-description-controlgroupjumpto05 = 跳转至编队 5
hotkey-description-controlgroupjumpto06 = 跳转至编队 6
hotkey-description-controlgroupjumpto07 = 跳转至编队 7
hotkey-description-controlgroupjumpto08 = 跳转至编队 8
hotkey-description-controlgroupjumpto09 = 跳转至编队 9
hotkey-description-controlgroupjumpto10 = 跳转至编队 0
hotkey-description-removefromcontrolgroup = 从编队移除

## editor.yaml
hotkey-description-editorundo = 撤销
hotkey-description-editorredo = 重做
hotkey-description-editorcopy = 复制
hotkey-description-editorquicksave = 保存地图
hotkey-description-editorpaste = 粘贴
hotkey-description-editordeleteselection = 删除选择
hotkey-description-editorselecttab = 选择标签页
hotkey-description-editortilestab = 地块标签页
hotkey-description-editoroverlaystab = 覆盖物标签页
hotkey-description-editoractorstab = 单位标签页
hotkey-description-editortoolstab = 工具标签页
hotkey-description-editorhistorytab = 历史标签页
hotkey-description-editorsettingstab = 设置标签页
hotkey-description-editortogglegridoverlay = 网格覆盖
hotkey-description-editortogglebuildableoverlay = 可建造地形覆盖
hotkey-description-editortogglemarkeroverlay = 标记层覆盖

## game.yaml
hotkey-description-cyclebase = 跳转至基地
hotkey-description-tolastevent = 跳转至最近雷达事件
hotkey-description-toselection = 跳转至选择
hotkey-description-selectallunits = 选择所有战斗单位
hotkey-description-selectunitsbytype = 按类型选择单位
hotkey-description-cycleharvesters = 切换采矿车
hotkey-description-pause = 暂停 / 取消暂停
hotkey-description-sell = 出售模式
hotkey-description-repair = 维修模式
hotkey-description-placebeacon = 放置信标
hotkey-description-cyclestatusbars = 切换状态栏显示
hotkey-description-togglemute = 切换静音
hotkey-description-toggleplayerstancecolor = 切换关系颜色
hotkey-description-takescreenshot = 截图
hotkey-description-attackmove = 攻击移动
hotkey-description-stop = 停止
hotkey-description-scatter = 散开
hotkey-description-deploy = 部署
hotkey-description-guard = 守卫
hotkey-description-stanceattackanything = 攻击任何目标
hotkey-description-stancedefend = 防御
hotkey-description-stancereturnfire = 还击
hotkey-description-stanceholdfire = 停火
hotkey-description-stopmusic = 停止
hotkey-description-pausemusic = 暂停或继续
hotkey-description-prevmusic = 上一首
hotkey-description-nextmusic = 下一首

## observer.yaml
hotkey-description-observercombinedview = 所有玩家
hotkey-description-observerworldview = 关闭战争迷雾
hotkey-description-replayspeedslow = 慢速
hotkey-description-replayspeedregular = 常速
hotkey-description-replayspeedfast = 快速
hotkey-description-replayspeedmax = 最快
hotkey-description-statisticsnone = 关闭统计
hotkey-description-statisticsbasic = 基本统计
hotkey-description-statisticseconomy = 经济统计
hotkey-description-statisticsproduction = 生产统计
hotkey-description-statisticssupportpowers = 支援技能统计
hotkey-description-statisticscombat = 战斗统计
hotkey-description-statisticsarmy = 军队统计
hotkey-description-statisticsgraph = 统计图表
hotkey-description-statisticsarmygraph = 军队价值图表

## production-common.yaml
hotkey-description-cycleproductionbuildings = 下一建筑
hotkey-description-selectproductionbuilding = 当前建筑
hotkey-description-production01 = 栏位 01
hotkey-description-production02 = 栏位 02
hotkey-description-production03 = 栏位 03
hotkey-description-production04 = 栏位 04
hotkey-description-production05 = 栏位 05
hotkey-description-production06 = 栏位 06
hotkey-description-production07 = 栏位 07
hotkey-description-production08 = 栏位 08
hotkey-description-production09 = 栏位 09
hotkey-description-production10 = 栏位 10
hotkey-description-production11 = 栏位 11
hotkey-description-production12 = 栏位 12
hotkey-description-production13 = 栏位 13
hotkey-description-production14 = 栏位 14
hotkey-description-production15 = 栏位 15
hotkey-description-production16 = 栏位 16
hotkey-description-production17 = 栏位 17
hotkey-description-production18 = 栏位 18
hotkey-description-production19 = 栏位 19
hotkey-description-production20 = 栏位 20
hotkey-description-production21 = 栏位 21
hotkey-description-production22 = 栏位 22
hotkey-description-production23 = 栏位 23
hotkey-description-production24 = 栏位 24

## supportpowers.yaml
hotkey-description-supportpower01 = 栏位 01
hotkey-description-supportpower02 = 栏位 02
hotkey-description-supportpower03 = 栏位 03
hotkey-description-supportpower04 = 栏位 04
hotkey-description-supportpower05 = 栏位 05
hotkey-description-supportpower06 = 栏位 06

## viewport.yaml
hotkey-description-mapscrollup = 向上滚动
hotkey-description-mapscrolldown = 向下滚动
hotkey-description-mapscrollleft = 向左滚动
hotkey-description-mapscrollright = 向右滚动
hotkey-description-mapjumptotopedge = 跳转至地图顶端
hotkey-description-mapjumptobottomedge = 跳转至地图底端
hotkey-description-mapjumptoleftedge = 跳转至地图左端
hotkey-description-mapjumptorightedge = 跳转至地图右端
hotkey-description-mapbookmarksave01 = 记录书签 1
hotkey-description-mapbookmarkrestore01 = 跳转至书签 1
hotkey-description-mapbookmarksave02 = 记录书签 2
hotkey-description-mapbookmarkrestore02 = 跳转至书签 2
hotkey-description-mapbookmarksave03 = 记录书签 3
hotkey-description-mapbookmarkrestore03 = 跳转至书签 3
hotkey-description-mapbookmarksave04 = 记录书签 4
hotkey-description-mapbookmarkrestore04 = 跳转至书签 4
hotkey-description-zoomin = 放大
hotkey-description-zoomout = 缩小
hotkey-description-resetzoom = 重置缩放
hotkey-description-disableuserinterface = 隐藏界面
hotkey-description-disablealluserinterface = 隐藏额外界面
