#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is
 * made available to you under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 * For more information, see COPYING.
 */
#endregion

using System;
using System.Reflection;
using NUnit.Framework;
using OpenRA.Mods.AI;
using OpenRA.Mods.Common.AI;
using OpenRA.Mods.Common.Traits;
using OpenRA.Traits;

namespace OpenRA.Test.OpenRA.Mods.AI
{
	/// <summary>
	/// End-to-end test for the M1 strategic decision loop.
	/// <para>
	/// The test drives the production
	/// <see cref="StrategicCommanderBotModule.EvaluateDecision"/> method
	/// against a real <see cref="RuleAttackPolicy"/> and a real
	/// <see cref="StrategicActionExecutor"/>, with stub
	/// <see cref="IStrategicStateProvider"/> and
	/// <see cref="IBotAttackController"/> implementations substituted
	/// in via the production test seams (the virtual
	/// <c>GetStateProvider / GetExecutor / GetPolicy / GetWorldTick /
	/// GetIsReplay</c> accessors on the commander, and the virtual
	/// <c>FindAttackController</c> accessor on the executor).
	/// </para>
	/// <para>
	/// The production code runs unchanged; the test only substitutes
	/// the actor/player-actor lookups that the production code uses to
	/// discover the state provider and the executor's controller.
	/// The seams are a permanent part of the production classes so
	/// that the same evidence can be regenerated by future batches.
	/// </para>
	/// <para>
	/// The harness does not exercise the world tick driver, because
	/// that path requires a fully-bootstrapped game (SDL platform,
	/// real Player, real Map). The production replay guard is
	/// verified by overriding <c>GetIsReplay</c>; the production
	/// <c>ModularBot</c> activation guard is verified by inspection
	/// of the upstream code.
	/// </para>
	/// </summary>
	[TestFixture]
	sealed class StrategicCommanderEndToEndTest
	{
		sealed class FakeStateProvider : IStrategicStateProvider
		{
			readonly StrategicObservation observation;
			public int CaptureCount;

			public FakeStateProvider(StrategicObservation observation)
			{
				this.observation = observation;
			}

			StrategicObservation IStrategicStateProvider.Capture(IBot bot)
			{
				CaptureCount++;
				return observation;
			}
		}

		sealed class RecordingAttackController : IBotAttackController
		{
			readonly BotAttackReadiness readiness;
			readonly StrategicActionResult response;
			public int RequestCount;
			public IBot LastBot;
			public StrategicAction LastAction;

			public RecordingAttackController(BotAttackReadiness readiness, StrategicActionResult response)
			{
				this.readiness = readiness;
				this.response = response;
			}

			BotAttackReadiness IBotAttackController.GetAttackReadiness() => readiness;

			StrategicActionResult IBotAttackController.RequestAttack(IBot bot, in StrategicAction action)
			{
				RequestCount++;
				LastBot = bot;
				LastAction = action;
				return response;
			}
		}

		sealed class FakeBot : IBot
		{
			public FakeBot(IBotInfo info) { Info = info; }
			public IBotInfo Info { get; }
			public Player Player => null;
			void IBot.Activate(Player p) { }
			void IBot.QueueOrder(Order order) { }
		}

		sealed class FakeBotInfo : IBotInfo
		{
			public FakeBotInfo(string type, string name) { Type = type; Name = name; }
			public string Type { get; }
			public string Name { get; }
		}

		// Drives the real production StrategicActionExecutor against a
		// controlled IBotAttackController, bypassing the production
		// actor/player-actor lookup (which requires a fully-bootstrapped
		// World). The world tick is replaced by an explicit parameter
		// that the test controls.
		sealed class TestableExecutor : StrategicActionExecutor, IStrategicActionExecutor
		{
			readonly IBotAttackController controller;
			readonly int worldTick;

			public TestableExecutor(IBotAttackController controller, int worldTick)
				: base(null, new StrategicActionExecutorInfo())
			{
				this.controller = controller;
				this.worldTick = worldTick;
			}

			internal override IBotAttackController FindAttackController(IBot bot) => controller;
			internal override int GetCurrentWorldTick() => worldTick;
		}

		// Production StrategicCommanderBotModule requires an Actor in
		// its constructor. The test subclass overrides all four seam
		// methods so the real Actor is never dereferenced. The world
		// tick and replay flag are mutable so cadence tests can drive
		// BotTick across multiple simulated ticks. The policy is
		// produced by the production GetPolicy() seam by default, and
		// can be replaced via SetPolicy() for throwing-policy tests.
		sealed class TestCommander : StrategicCommanderBotModule
		{
			readonly IStrategicStateProvider stateProvider;
			readonly IStrategicActionExecutor executor;
			readonly IBotAttackController enabledAttackController;
			IStrategicPolicy policy;

			public int WorldTickValue;
			public bool IsReplayValue;

			public TestCommander(
				StrategicCommanderBotModuleInfo info,
				IStrategicStateProvider stateProvider,
				IStrategicActionExecutor executor,
				int worldTick,
				bool isReplay,
				IBotAttackController enabledAttackController = null)
				: base(null, info)
			{
				this.stateProvider = stateProvider;
				this.executor = executor;
				this.enabledAttackController = enabledAttackController;
				WorldTickValue = worldTick;
				IsReplayValue = isReplay;

				/*
				 * The trait's enabledAtTick defaults to 0 so the
				 * existing 75-tick cadence tests keep their
				 * assumption that the trait was enabled at world
				 * start. Tests that need a different offset call
				 * SetEnabledAtTickForTest().
				 */
				SetEnabledAtTickForTest(0);
			}

			internal override IStrategicStateProvider GetStateProvider() => stateProvider;
			internal override IStrategicActionExecutor GetExecutor() => executor;
			internal override IStrategicPolicy GetPolicy() => policy ?? base.GetPolicy();
			internal override int GetWorldTick() => WorldTickValue;
			internal override bool GetIsReplay() => IsReplayValue;
			internal override IBotAttackController FindEnabledAttackController() => enabledAttackController;

			public void BotTickPublic(IBot bot, int worldTick)
			{
				WorldTickValue = worldTick;
				((IBotTick)this).BotTick(bot);
			}

			public void SetPolicy(IStrategicPolicy newPolicy) { policy = newPolicy; }
		}

		static StrategicObservation MakeObservation(int worldTick, int available, int activeSquads)
		{
			return new StrategicObservation("1.0.0", worldTick, "Multi0", "ra", 0, available, activeSquads);
		}

		static StrategicCommanderBotModuleInfo MakeInfo(int squadSize = 40, int interval = 75)
		{
			return new StrategicCommanderBotModuleInfo
			{
				DecisionIntervalTicks = interval,
				SquadSize = squadSize,
			};
		}

		[TestCase(TestName = "ATTACK request flows policy -> real executor -> IBotAttackController and records EXECUTED")]
		public void AttackRequestFlowsThroughProductionChain()
		{
			Log.AddChannel("strategic", null);

			var info = MakeInfo();

			var fakeState = new FakeStateProvider(MakeObservation(750, 40, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult(
					"1.0.0", 750,
					StrategicActionType.Attack,
					StrategicActionStatus.Executed,
					StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 750);

			var commander = new TestCommander(info, fakeState, executor, worldTick: 750, isReplay: false);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			commander.EvaluateDecision(bot);

			Assert.That(fakeState.CaptureCount, Is.EqualTo(1),
				"State provider should be invoked exactly once per decision.");
			Assert.That(controller.RequestCount, Is.EqualTo(1),
				"Attack controller should be invoked exactly once when policy emits ATTACK.");
			Assert.That(controller.LastBot, Is.SameAs(bot),
				"Attack controller should be invoked with the supplied IBot.");
			Assert.That(controller.LastAction.Type, Is.EqualTo(StrategicActionType.Attack));

			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1));
			var recorded = commander.DecisionLog.Events[0];
			Assert.That(recorded.ActionType, Is.EqualTo(StrategicActionType.Attack));
			Assert.That(recorded.Status, Is.EqualTo(StrategicActionStatus.Executed));
			Assert.That(recorded.WorldTick, Is.EqualTo(750));
			Assert.That(recorded.SchemaVersion, Is.EqualTo("1.0.0"));
			Assert.That(recorded.BotType, Is.EqualTo("strategic"));
		}

		[TestCase(TestName = "NO_OP short-circuit records NoOp/NONE without invoking the controller")]
		public void NoOpShortCircuits()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			// available < squadSize => policy emits NO_OP
			var fakeState = new FakeStateProvider(MakeObservation(1000, 4, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(4, 0),
				new StrategicActionResult("1.0.0", 1000, StrategicActionType.NoOp, StrategicActionStatus.NoOp, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 1000);

			var commander = new TestCommander(info, fakeState, executor, worldTick: 1000, isReplay: false);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			commander.EvaluateDecision(bot);

			Assert.That(controller.RequestCount, Is.EqualTo(0),
				"NO_OP should not dispatch to the attack controller.");
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1));
			Assert.That(commander.DecisionLog.Events[0].ActionType, Is.EqualTo(StrategicActionType.NoOp));
			Assert.That(commander.DecisionLog.Events[0].Status, Is.EqualTo(StrategicActionStatus.NoOp));
		}

		[TestCase(TestName = "Replay guard: BotTick records nothing when world.IsReplay is true")]
		public void ReplayGuardSkipsPolicy()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			var fakeState = new FakeStateProvider(MakeObservation(250, 50, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(50, 0),
				new StrategicActionResult("1.0.0", 250, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 250);

			var commander = new TestCommander(info, fakeState, executor, worldTick: 250, isReplay: true);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			// BotTick is the production entry point. The replay guard
			// short-circuits before the policy runs.
			((IBotTick)commander).BotTick(bot);

			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(0),
				"Replay playback must not record any strategic decisions.");
		}

		[TestCase(TestName = "Real StrategicActionExecutor: version mismatch rejected as INVALID_ACTION")]
		public void ExecutorRejectsVersionMismatch()
		{
			Log.AddChannel("strategic", null);

			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult(
					"1.0.0", 1500,
					StrategicActionType.Attack,
					StrategicActionStatus.Executed,
					StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 1500);

			var badVersion = new StrategicAction("0.9.0", 1500, StrategicActionType.Attack);
			var result = ((IStrategicActionExecutor)executor).Execute(new FakeBot(new FakeBotInfo("strategic", "Strategic")), in badVersion);

			Assert.That(result.Status, Is.EqualTo(StrategicActionStatus.Rejected));
			Assert.That(result.Reason, Is.EqualTo(StrategicActionReason.InvalidAction));
			Assert.That(controller.RequestCount, Is.EqualTo(0),
				"Controller must not be invoked when the schema version mismatches.");
		}

		[TestCase(TestName = "Real StrategicActionExecutor: stale tick rejected as INVALID_ACTION")]
		public void ExecutorRejectsStaleTick()
		{
			Log.AddChannel("strategic", null);

			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult(
					"1.0.0", 1500,
					StrategicActionType.Attack,
					StrategicActionStatus.Executed,
					StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 1500);

			var stale = new StrategicAction("1.0.0", 1499, StrategicActionType.Attack);
			var result = ((IStrategicActionExecutor)executor).Execute(new FakeBot(new FakeBotInfo("strategic", "Strategic")), in stale);

			Assert.That(result.Status, Is.EqualTo(StrategicActionStatus.Rejected));
			Assert.That(result.Reason, Is.EqualTo(StrategicActionReason.InvalidAction));
			Assert.That(controller.RequestCount, Is.EqualTo(0),
				"Controller must not be invoked when the action's world tick is stale.");
		}

		[TestCase(TestName = "Real StrategicActionExecutor: NO_OP short-circuit does not call controller")]
		public void ExecutorNoOpShortCircuits()
		{
			Log.AddChannel("strategic", null);

			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult(
					"1.0.0", 1500,
					StrategicActionType.Attack,
					StrategicActionStatus.Executed,
					StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 1500);

			var noop = new StrategicAction("1.0.0", 1500, StrategicActionType.NoOp);
			var result = ((IStrategicActionExecutor)executor).Execute(new FakeBot(new FakeBotInfo("strategic", "Strategic")), in noop);

			Assert.That(result.Status, Is.EqualTo(StrategicActionStatus.NoOp));
			Assert.That(result.Reason, Is.EqualTo(StrategicActionReason.None));
			Assert.That(controller.RequestCount, Is.EqualTo(0));
		}

		[TestCase(TestName = "Executor rejects with EXECUTOR_UNAVAILABLE when no controller is found")]
		public void ExecutorReportsExecutorUnavailable()
		{
			Log.AddChannel("strategic", null);

			var executor = new TestableExecutor(controller: null, worldTick: 1500);

			var attack = new StrategicAction("1.0.0", 1500, StrategicActionType.Attack);
			var result = ((IStrategicActionExecutor)executor).Execute(new FakeBot(new FakeBotInfo("strategic", "Strategic")), in attack);

			Assert.That(result.Status, Is.EqualTo(StrategicActionStatus.Rejected));
			Assert.That(result.Reason, Is.EqualTo(StrategicActionReason.ExecutorUnavailable));
		}

		[TestCase(TestName = "BotTick fires the first decision after exactly DecisionIntervalTicks (default 75)")]
		public void FirstDecisionFiresAt75Ticks()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();
			Assert.That(info.DecisionIntervalTicks, Is.EqualTo(75),
				"M1 spec requires the first decision after 75 world ticks of enabled operation.");

			var fakeState = new FakeStateProvider(MakeObservation(0, 40, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 0, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 0);
			var commander = new TestCommander(info, fakeState, executor, worldTick: 0, isReplay: false);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			// Tick 1..74: nothing happens. Tick 75: first decision runs.
			for (var i = 1; i <= 74; i++)
			{
				commander.BotTickPublic(bot, worldTick: i);
				Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(0),
					$"No decision expected before tick 75 (current={i}).");
			}

			commander.BotTickPublic(bot, worldTick: 75);
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1),
				"First decision must fire on tick 75.");
			Assert.That(controller.RequestCount, Is.EqualTo(1));
		}

		[TestCase(TestName = "BotTick fires repeated decisions on the 75-tick cadence")]
		public void RepeatedDecisionsFireOn75TickCadence()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			var fakeState = new FakeStateProvider(MakeObservation(0, 40, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 0, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 0);
			var commander = new TestCommander(info, fakeState, executor, worldTick: 0, isReplay: false);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			commander.BotTickPublic(bot, worldTick: 75);
			commander.BotTickPublic(bot, worldTick: 150);
			commander.BotTickPublic(bot, worldTick: 225);

			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(3),
				"Three decisions must have been recorded across three cadence boundaries.");
			Assert.That(controller.RequestCount, Is.EqualTo(3));
		}

		[TestCase(TestName = "State-capture exception is contained and recorded as NO_OP/FAILED/POLICY_ERROR")]
		public void StateCaptureExceptionIsContained()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			var fakeState = new ThrowingStateProvider();
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 750);
			var commander = new TestCommander(info, fakeState, executor, worldTick: 750, isReplay: false);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			Assert.DoesNotThrow(() => commander.EvaluateDecision(bot),
				"State-capture exceptions must be caught by the commander.");
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1));
			var recorded = commander.DecisionLog.Events[0];
			Assert.That(recorded.ActionType, Is.EqualTo(StrategicActionType.NoOp));
			Assert.That(recorded.Status, Is.EqualTo(StrategicActionStatus.Failed));
			Assert.That(recorded.Reason, Is.EqualTo(StrategicActionReason.PolicyError));
			Assert.That(recorded.ExceptionType, Is.EqualTo(typeof(InvalidOperationException).FullName));
			Assert.That(controller.RequestCount, Is.EqualTo(0),
				"Controller must not be invoked when state capture failed.");
		}

		[TestCase(TestName = "Executor exception is recorded as ATTACK/FAILED/EXECUTOR_UNAVAILABLE")]
		public void ExecutorExceptionIsContained()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			var fakeState = new FakeStateProvider(MakeObservation(750, 40, 0));
			var executor = new ThrowingExecutor();
			var commander = new TestCommander(info, fakeState, executor, worldTick: 750, isReplay: false);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			Assert.DoesNotThrow(() => commander.EvaluateDecision(bot),
				"Executor exceptions must be caught by the commander.");
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1));
			var recorded = commander.DecisionLog.Events[0];
			Assert.That(recorded.ActionType, Is.EqualTo(StrategicActionType.Attack));
			Assert.That(recorded.Status, Is.EqualTo(StrategicActionStatus.Failed));
			Assert.That(recorded.Reason, Is.EqualTo(StrategicActionReason.ExecutorUnavailable));
			Assert.That(recorded.ExceptionType, Is.EqualTo(typeof(InvalidOperationException).FullName));
		}

		[TestCase(TestName = "Policy threshold is sourced from configured SquadSize, not from the observation")]
		public void PolicyThresholdIsSourcedFromConfigNotObservation()
		{
			Log.AddChannel("strategic", null);

			/*
			 * Configure SquadSize: 8 — small enough to be reached by
			 * the supplied observation. If the policy still pulled
			 * the threshold from a hidden observation field (the
			 * historical bug), the count of 8 would not be enough
			 * to satisfy the historical default of 40 and the
			 * policy would emit NO_OP.
			 */
			var info = MakeInfo(squadSize: 8);

			var fakeState = new FakeStateProvider(MakeObservation(750, 8, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(8, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 750);
			var commander = new TestCommander(info, fakeState, executor, worldTick: 750, isReplay: false);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			commander.EvaluateDecision(bot);

			Assert.That(controller.RequestCount, Is.EqualTo(1),
				"Policy must use the configured SquadSize (8), not a hidden observation field with a default of 40.");
			Assert.That(commander.DecisionLog.Events[0].ActionType, Is.EqualTo(StrategicActionType.Attack));
		}

		[TestCase(TestName = "Identical observations under different configured thresholds produce different actions")]
		public void ObservationWithSquadSizeHintDoesNotInfluencePolicy()
		{
			Log.AddChannel("strategic", null);

			var controllerA = new RecordingAttackController(
				new BotAttackReadiness(8, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executorA = new TestableExecutor(controllerA, worldTick: 750);
			var commanderA = new TestCommander(MakeInfo(squadSize: 4), new FakeStateProvider(MakeObservation(750, 8, 0)), executorA, 750, false);
			commanderA.EvaluateDecision(new FakeBot(new FakeBotInfo("strategic", "Strategic")));

			var controllerB = new RecordingAttackController(
				new BotAttackReadiness(8, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executorB = new TestableExecutor(controllerB, worldTick: 750);
			var commanderB = new TestCommander(MakeInfo(squadSize: 100), new FakeStateProvider(MakeObservation(750, 8, 0)), executorB, 750, false);
			commanderB.EvaluateDecision(new FakeBot(new FakeBotInfo("strategic", "Strategic")));

			Assert.That(commanderA.DecisionLog.Events[0].ActionType, Is.EqualTo(StrategicActionType.Attack),
				"SquadSize: 4 with 8 available units must emit ATTACK.");
			Assert.That(commanderB.DecisionLog.Events[0].ActionType, Is.EqualTo(StrategicActionType.NoOp),
				"SquadSize: 100 with 8 available units must emit NO_OP. The threshold is config-driven; identical observations must not yield identical actions.");
		}

		[TestCase(TestName = "Throwing policy is contained and recorded as NO_OP/FAILED/POLICY_ERROR")]
		public void ThrowingPolicyIsContained()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			var fakeState = new FakeStateProvider(MakeObservation(750, 40, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 750);
			var commander = new TestCommander(info, fakeState, executor, worldTick: 750, isReplay: false);
			commander.SetPolicy(new ThrowingPolicy());
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			Assert.DoesNotThrow(() => commander.EvaluateDecision(bot),
				"Policy exceptions must be caught by the commander.");
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1));
			var recorded = commander.DecisionLog.Events[0];
			Assert.That(recorded.ActionType, Is.EqualTo(StrategicActionType.NoOp));
			Assert.That(recorded.Status, Is.EqualTo(StrategicActionStatus.Failed));
			Assert.That(recorded.Reason, Is.EqualTo(StrategicActionReason.PolicyError));
			Assert.That(recorded.ExceptionType, Is.EqualTo(typeof(InvalidOperationException).FullName));
			Assert.That(controller.RequestCount, Is.EqualTo(0),
				"Controller must not be invoked when the policy raised an exception.");

			// Recovery check: a follow-up decision with a non-throwing
			// policy must succeed. Proves the commander is not wedged
			// by the previous exception.
			commander.SetPolicy(null);
			commander.EvaluateDecision(bot);
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(2));
			Assert.That(commander.DecisionLog.Events[1].Status, Is.EqualTo(StrategicActionStatus.Executed));
		}

		[TestCase(TestName = "DecisionIntervalTicks: zero is rejected at ruleset load")]
		public void DecisionIntervalTicksRejectedAtZero()
		{
			// The production RulesetLoaded guard throws a
			// YamlException for DecisionIntervalTicks <= 0. The
			// test cannot easily stand up a full Ruleset, so it
			// exercises the same validation path via reflection.
			// This pins the contract: a config of 0 must never
			// reach production code, otherwise modulo-by-zero
			// would surface at the first BotTick.
			var method = typeof(StrategicCommanderBotModuleInfo).GetMethod(
				"RulesetLoaded",
				System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
			Assert.That(method, Is.Not.Null);

			var bad = new StrategicCommanderBotModuleInfo
			{
				DecisionIntervalTicks = 0,
				SquadSize = 40,
			};

			/*
			 * Reflection wraps the thrown YamlException in a
			 * TargetInvocationException; unwrap it so the
			 * production error type is what the test pins.
			 */
			var caught = Assert.Throws<TargetInvocationException>(() => method.Invoke(bad, [null, null]));
			Assert.That(caught.InnerException, Is.TypeOf<YamlException>());
		}

		[TestCase(TestName = "SquadSize: zero is rejected at ruleset load")]
		public void SquadSizeRejectedAtZero()
		{
			var info = new StrategicCommanderBotModuleInfo
			{
				DecisionIntervalTicks = 75,
				SquadSize = 0,
			};
			var method = typeof(StrategicCommanderBotModuleInfo).GetMethod(
				"RulesetLoaded",
				System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
			Assert.That(method, Is.Not.Null);

			var caught = Assert.Throws<TargetInvocationException>(() => method.Invoke(info, [null, null]));
			Assert.That(caught.InnerException, Is.TypeOf<YamlException>());
		}

		// Cross-check that the commander's configured SquadSize
		// agrees with the single External SquadManager on the
		// same actor. The rule policy and the controller both
		// derive their formation threshold from configuration; a
		// silent mismatch would desynchronise observation and
		// execution, so RulesetLoaded must raise a YamlException
		// rather than let the match start in an inconsistent
		// state. The cross-check is intentionally scoped to the
		// unique-External pairing, not a global "every
		// SquadManager matches" check -- the RA player has
		// multiple SquadManager instances (Rush/Normal/Strategic
		// External/Turtle/Naval) with different SquadSizes that
		// serve other bot types and must not be compared.
		[TestCase(TestName = "SquadSize mismatch with the External SquadManager is rejected at ruleset load")]
		public void SquadSizeMismatchWithSquadManagerIsRejectedAtLoad()
		{
			var sm = NewSquadManager(40, StrategyControl.External);
			var actorInfo = new ActorInfo("player", sm);
			var caught = Assert.Throws<YamlException>(
				() => StrategicCommanderBotModuleInfo.ValidateSquadSizeConsistency(
					commanderSquadSize: 8,
					ai: actorInfo));
			Assert.That(caught.Message, Does.Contain("SquadSize"),
				"The YamlException must name the SquadSize mismatch so the misconfiguration is easy to localise.");
		}

		[TestCase(TestName = "SquadSize agreement with the External SquadManager is accepted at ruleset load")]
		public void SquadSizeAgreementWithSquadManagerIsAcceptedAtLoad()
		{
			var sm = NewSquadManager(40, StrategyControl.External);
			var actorInfo = new ActorInfo("player", sm);
			Assert.DoesNotThrow(
				() => StrategicCommanderBotModuleInfo.ValidateSquadSizeConsistency(
					commanderSquadSize: 40,
					ai: actorInfo),
				"ValidateSquadSizeConsistency must accept a commander whose SquadSize matches the single External SquadManager on the same actor.");
		}

		// Synthetic RA-style mixed config: five SquadManager
		// instances on the same player actor, only the Strategic
		// External one participates in the cross-check. The other
		// four (Rush, Normal, Turtle, Naval) are autonomous bot
		// types and must not cause a false positive even though
		// their SquadSizes differ from the commander's 40. This
		// is the regression that blocked RA loading in the
		// previous round. The numbers below match the real RA
		// player config (rush=20, normal=40, strategic=40,
		// turtle=10, naval=1) so the test exercises the actual
		// production values.
		[TestCase(TestName = "RA-style mixed config is accepted when only the External SquadManager matches")]
		public void RAMixedConfigIsAcceptedWhenExternalSquadSizeMatches()
		{
			var playerActor = new ActorInfo(
				"player",
				NewSquadManager(20, StrategyControl.Autonomous),  // rush
				NewSquadManager(40, StrategyControl.Autonomous),  // normal
				NewSquadManager(40, StrategyControl.External),   // strategic
				NewSquadManager(10, StrategyControl.Autonomous),  // turtle
				NewSquadManager(1, StrategyControl.Autonomous));  // naval

			Assert.DoesNotThrow(
				() => StrategicCommanderBotModuleInfo.ValidateSquadSizeConsistency(
					commanderSquadSize: 40,
					ai: playerActor),
				"RA's mixed-bot config must not trigger a false positive: only the External SquadManager participates in the cross-check.");
		}

		[TestCase(TestName = "Missing External SquadManager is rejected at ruleset load")]
		public void MissingExternalSquadManagerIsRejectedAtLoad()
		{
			var playerActor = new ActorInfo(
				"player",
				NewSquadManager(40, StrategyControl.Autonomous));

			var caught = Assert.Throws<YamlException>(
				() => StrategicCommanderBotModuleInfo.ValidateSquadSizeConsistency(
					commanderSquadSize: 40,
					ai: playerActor));
			Assert.That(caught.Message, Does.Contain("exactly one"),
				"The YamlException must explain that exactly one External controller is required.");
		}

		[TestCase(TestName = "Two External SquadManagers are rejected at ruleset load")]
		public void TwoExternalSquadManagersAreRejectedAtLoad()
		{
			var playerActor = new ActorInfo(
				"player",
				NewSquadManager(40, StrategyControl.External),
				NewSquadManager(40, StrategyControl.External));

			var caught = Assert.Throws<YamlException>(
				() => StrategicCommanderBotModuleInfo.ValidateSquadSizeConsistency(
					commanderSquadSize: 40,
					ai: playerActor));
			Assert.That(caught.Message, Does.Contain("exactly one"),
				"The YamlException must explain that exactly one External controller is required.");
		}

		[TestCase(TestName = "External SquadSize mismatch is rejected even with mixed bot types")]
		public void ExternalMismatchIsRejectedWithMixedBotTypes()
		{
			var playerActor = new ActorInfo(
				"player",
				NewSquadManager(20, StrategyControl.Autonomous),  // rush
				NewSquadManager(40, StrategyControl.Autonomous),  // normal
				NewSquadManager(8, StrategyControl.External),    // strategic -- wrong SquadSize
				NewSquadManager(10, StrategyControl.Autonomous),  // turtle
				NewSquadManager(1, StrategyControl.Autonomous));  // naval

			var caught = Assert.Throws<YamlException>(
				() => StrategicCommanderBotModuleInfo.ValidateSquadSizeConsistency(
					commanderSquadSize: 40,
					ai: playerActor));
			Assert.That(caught.Message, Does.Contain("SquadSize"),
				"The YamlException must name the SquadSize mismatch on the External controller.");
		}

		[TestCase(TestName = "ValidateSquadSizeConsistency handles a null ActorInfo")]
		public void ValidateSquadSizeConsistencyAcceptsNullActorInfo()
		{
			Assert.Throws<YamlException>(
				() => StrategicCommanderBotModuleInfo.ValidateSquadSizeConsistency(40, null),
				"ValidateSquadSizeConsistency must throw if the actor info is null (the commander must live on a player actor).");
		}

		// Helper that builds a SquadManagerBotModuleInfo with a
		// chosen SquadSize and StrategyControl. Both fields are
		// readonly, so reflection is used to plant non-default
		// values.
		static SquadManagerBotModuleInfo NewSquadManager(int squadSize, StrategyControl control)
		{
			var sm = new SquadManagerBotModuleInfo();
			typeof(SquadManagerBotModuleInfo).GetField("SquadSize").SetValue(sm, squadSize);
			typeof(SquadManagerBotModuleInfo).GetField("StrategyControl").SetValue(sm, control);
			return sm;
		}

		[TestCase(TestName = "First decision fires 75 ticks after the trait is enabled, not at the next global multiple of 75")]
		public void FirstDecisionDeferedUntilEnabledPlus75Ticks()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			var fakeState = new FakeStateProvider(MakeObservation(0, 40, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 0, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 0);
			var commander = new TestCommander(info, fakeState, executor, worldTick: 0, isReplay: false);

			/*
			 * Trait is enabled at world tick 50 (not 0).
			 */
			commander.SetEnabledAtTickForTest(50);
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			// Ticks 50..124: 0..74 ticks of enabled operation -- no decision.
			for (var i = 50; i < 125; i++)
			{
				commander.BotTickPublic(bot, worldTick: i);
				Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(0),
					$"No decision expected at tick {i} (< 75 ticks of enabled operation).");
			}

			// Tick 125: 75 ticks of enabled operation -- first decision.
			commander.BotTickPublic(bot, worldTick: 125);
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1),
				"First decision must fire exactly 75 ticks after the trait is enabled, not at the next global multiple of 75.");
			Assert.That(controller.RequestCount, Is.EqualTo(1));
		}

		[TestCase(TestName = "Init failure is recorded when the state provider is missing, and BotTick short-circuits")]
		public void InitFailureRecordedWhenStateProviderMissing()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			// The TestCommander in this test passes `null` for the
			// state provider to the production GetStateProvider()
			// seam, simulating a missing controller. The commander
			// must record the failure when its init check runs
			// (production runs it from TraitEnabled; the test
			// invokes EnsureInitialized() directly because the
			// trait lifecycle is not bootstrapped in the unit
			// harness) and refuse to evaluate any decision
			// afterwards.
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 0);
			var commander = new TestCommander(info, stateProvider: null, executor, worldTick: 0, isReplay: false);
			commander.EnsureInitialized();
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			Assert.That(commander.InitFailed, Is.True,
				"Init failure must be flagged on the commander when the state provider is missing.");
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1));
			var recorded = commander.DecisionLog.Events[0];
			Assert.That(recorded.ActionType, Is.EqualTo(StrategicActionType.NoOp));
			Assert.That(recorded.Status, Is.EqualTo(StrategicActionStatus.Failed));
			Assert.That(recorded.Reason, Is.EqualTo(StrategicActionReason.PolicyError));
			Assert.That(recorded.ExceptionMessage, Does.Contain("IStrategicStateProvider"),
				"The init-failure event must name the missing component.");

			// BotTick must short-circuit on init failure -- no
			// additional events recorded even across many ticks.
			commander.BotTickPublic(bot, worldTick: 1000);
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1),
				"BotTick must not record additional decisions while init failure is flagged.");
			Assert.That(controller.RequestCount, Is.EqualTo(0));
		}

		[TestCase(TestName = "Init failure is recorded when the attack controller is missing, and BotTick short-circuits")]
		public void InitFailureRecordedWhenAttackControllerMissing()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			// The state provider is present and Capture() succeeds,
			// but the player's unique-enabled IBotAttackController
			// lookup returns null. The commander must record the
			// init failure exactly once at EnsureInitialized() and
			// every subsequent BotTick must short-circuit on
			// InitFailed without re-recording the failure.
			var fakeState = new FakeStateProvider(MakeObservation(0, 40, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 0);
			var commander = new TestCommander(
				info,
				fakeState,
				executor,
				worldTick: 0,
				isReplay: false,
				enabledAttackController: null);
			commander.EnsureInitialized();
			var bot = new FakeBot(new FakeBotInfo("strategic", "Strategic"));

			Assert.That(commander.InitFailed, Is.True,
				"Init failure must be flagged on the commander when no enabled IBotAttackController is found.");
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1),
				"EnsureInitialized must record exactly one init-failure event.");
			var recorded = commander.DecisionLog.Events[0];
			Assert.That(recorded.ActionType, Is.EqualTo(StrategicActionType.NoOp));
			Assert.That(recorded.Status, Is.EqualTo(StrategicActionStatus.Failed));
			Assert.That(recorded.Reason, Is.EqualTo(StrategicActionReason.PolicyError));
			Assert.That(recorded.ExceptionMessage, Does.Contain("IBotAttackController"),
				"The init-failure event must name the missing component.");

			// BotTick must short-circuit permanently; no further
			// events even after many cadence boundaries.
			commander.BotTickPublic(bot, worldTick: 75);
			commander.BotTickPublic(bot, worldTick: 150);
			commander.BotTickPublic(bot, worldTick: 225);
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1),
				"BotTick must not record additional decisions while init failure is flagged.");
			Assert.That(controller.RequestCount, Is.EqualTo(0));
		}

		[TestCase(TestName = "Init failure is recorded when the enabled attack controller is ambiguous")]
		public void InitFailureRecordedWhenAttackControllerAmbiguous()
		{
			Log.AddChannel("strategic", null);
			var info = MakeInfo();

			// Two enabled IBotAttackController implementations
			// would be ambiguous; the production selection rule
			// returns null in that case. The test exercises the
			// same null path through the override seam so the
			// commander records the same init-failure component.
			var fakeState = new FakeStateProvider(MakeObservation(0, 40, 0));
			var controller = new RecordingAttackController(
				new BotAttackReadiness(40, 0),
				new StrategicActionResult("1.0.0", 750, StrategicActionType.Attack, StrategicActionStatus.Executed, StrategicActionReason.None));
			var executor = new TestableExecutor(controller, worldTick: 0);
			var commander = new TestCommander(
				info,
				fakeState,
				executor,
				worldTick: 0,
				isReplay: false,
				enabledAttackController: null);
			commander.EnsureInitialized();

			Assert.That(commander.InitFailed, Is.True,
				"Init failure must be flagged when the enabled controller selection is ambiguous.");
			Assert.That(commander.DecisionLog.Events.Count, Is.EqualTo(1));
			Assert.That(commander.DecisionLog.Events[0].ExceptionMessage, Does.Contain("IBotAttackController"));
		}

		sealed class ThrowingStateProvider : IStrategicStateProvider
		{
			public int CaptureCount;
			StrategicObservation IStrategicStateProvider.Capture(IBot bot)
			{
				CaptureCount++;
				throw new InvalidOperationException("state capture boom");
			}
		}

		sealed class ThrowingExecutor : IStrategicActionExecutor
		{
			public StrategicActionResult Execute(IBot bot, in StrategicAction action)
			{
				throw new InvalidOperationException("executor boom");
			}
		}

		sealed class ThrowingPolicy : IStrategicPolicy
		{
			public StrategicAction Decide(in StrategicObservation observation)
			{
				throw new InvalidOperationException("policy boom");
			}
		}
	}
}
